### ISSUE TITLE
Possible to add DPI Scaling information?

### ISSUE THREAD

**Issue by xantari** [falahati/WindowsDisplayAPI#9]
Hi,

I couldn't find it in library (maybe I missed something). I am looking for DPI scaling information for each display.

Possible to add to library?

Thanks!

**Comment by falahati** [comment]
Unfortunately, DPI functionality is actually related to the CCD API set and therefore I am little hesitant to add this to the library. Especially since there seems to be no public programmatic way to change it as well if we ignore the fact that you can directly modify registry values.

In any case, the following is some information I gathered from my searches that might work for you and I might use to add to the library if I settled on the decision. I keep this issue open as a reminder.

[Information about how scaling values in Win8.1 works](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings)
[GDI's `GetDeviceCaps()` can be used to get the scaling factor](https://stackoverflow.com/a/21450169/1913051)
[ShellScaling's `GetDpiForMonitor()` can also be used to get the effective and raw DPI value for a monitor. `HMONITOR` can be retrieved using the GDI's `MonitorFromPoint()` function.](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor)
[There is actually a private API to set the scaling factor of a display using the CCD's `DisplayConfigSetDeviceInfo()` function. This, in fact, falls into the scope of this library.](https://stackoverflow.com/a/57397039/1913051)

**Comment by falahati** [comment]
DPI scaling properties added to the `DisplayConfigSource` class based on this code found at the following repository:
https://github.com/lihas/windows-DPI-scaling-sample

However, for some reason changing the DPI scale doesn't work now. I will release a new NuGet version as soon as I am able to get it working.
Meanwhile, if you are only interested in retrieving the DPI scaling factor, you can use the latest commit to do so.

**Comment by xantari** [comment]
Awesome! Thanks

**Comment by falahati** [comment]
Support added with the latest release.
